import java.util.Random;

public class SavingAccount {
    String accounttype;
    int accountholderage;
    long accountnumber;
    String accountholdername;
    int accountbalance;
    String accountstatus;

    public long autogeneratedAccountNo(){
        long branchcode = 4059;
        Random obj = new Random();
        long accountnumber = branchcode*100000000 + obj.nextLong(100000000L);
        return accountnumber;
    }
    public float deposit(float accountbalance, float depositeamount){
        float updatebalance = accountbalance + depositeamount;
        return updatebalance;
    }
    public float withdraw(float accountbalance, float withdrawamount){
        float updatebalance = accountbalance - withdrawamount;
        return updatebalance;
    }
    public float transfer(float accountbalance, float transferamount){
        float updatebalance = accountbalance - transferamount;
        return updatebalance;
    }
    public String Accountstatus(int accountbalance){
        if(accountbalance<0) {
            accountstatus = "Inactive";
        }
        else accountstatus = "Active";
            return accountstatus;
        }
        public int balance(){
            return accountbalance;
        }
}
